import PocketbaseSvelte, {
	type RecordService,
	type CollectionService,
	type CommonOptions
} from 'pocketbase-sveltekit';

// Generated by `vela sync` into .svelte-kit/types/pocketbase/$types.d.ts, which
// augments this module. Imported by the package's own name so it resolves to
// the same module identity the generated file augments.
// @ts-ignore
import type { Models, Collections } from '@velastack/pocketbase';

// Re-exported so the generated $types.d.ts can import them from this package,
// which is what it has always emitted.
export type {
	AuthCollectionModel,
	BaseCollectionModel,
	ViewCollectionModel
} from 'pocketbase-sveltekit';

/** `pb.collections`, narrowed against the generated `Collections` map. */
export declare class CollectionsCrudService extends CollectionService {
	getOne<C extends keyof Collections>(id: C, options?: CommonOptions): Promise<Collections[C]>;

	update<C extends keyof Collections>(
		id: C,
		bodyParams?:
			| {
					[key: string]: any;
			  }
			| FormData,
		options?: CommonOptions
	): Promise<Collections[C]>;

	delete(id: keyof Collections, options?: CommonOptions): Promise<boolean>;
}

/** A PocketBase client whose `collection()` returns records typed by the generated `Models`. */
export declare class Client extends PocketbaseSvelte {
	collections: CollectionsCrudService;
	collection<OverrideType = never, TId extends keyof Models = keyof Models>(
		idOrName: TId
	): RecordService<[OverrideType] extends [never] ? Models[TId] : OverrideType>;
}

declare global {
	namespace App {
		interface Locals {
			pb: Client;
			admin: Client;
			/** Only set when the app has a `teams` collection. */
			team?: string;
			/** Only set when the app has a `teams` collection. */
			role?: string;
			meta: {
				appName: string;
				appURL: string;
				senderName: string;
				senderAddress: string;
				hideControls: boolean;
			};
		}
	}
}
